version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: homework-tutor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: homework_tutor
      MYSQL_USER: homework_user
      MYSQL_PASSWORD: homework_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - homework-network
    restart: unless-stopped

  # PostgreSQL数据库（生产环境）
  postgres:
    image: postgres:15
    container_name: homework-tutor-postgres
    environment:
      POSTGRES_DB: homework_tutor
      POSTGRES_USER: homework_user
      POSTGRES_PASSWORD: homework_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - homework-network
    restart: unless-stopped
    profiles:
      - production

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: homework-tutor-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - homework-network
    restart: unless-stopped

  # MinIO对象存储
  minio:
    image: minio/minio:latest
    container_name: homework-tutor-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - homework-network
    restart: unless-stopped

  # API网关
  gateway:
    build:
      context: ../../backend/gateway
      dockerfile: Dockerfile
    container_name: homework-tutor-gateway
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - USER_SERVICE_URL=http://user-service:8080
      - HOMEWORK_SERVICE_URL=http://homework-service:8081
      - MISTAKE_SERVICE_URL=http://mistake-service:8082
      - CHAT_SERVICE_URL=http://chat-service:8083
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - homework-network
    restart: unless-stopped

  # 用户服务
  user-service:
    build:
      context: ../../backend/user-service
      dockerfile: Dockerfile
    container_name: homework-tutor-user-service
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=homework_user
      - DB_PASSWORD=homework_password
      - DB_NAME=homework_tutor
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-secret-key-here
    depends_on:
      - mysql
      - redis
    networks:
      - homework-network
    restart: unless-stopped

  # 作业服务
  homework-service:
    build:
      context: ../../backend/homework-service
      dockerfile: Dockerfile
    container_name: homework-tutor-homework-service
    ports:
      - "8081:8081"
    environment:
      - ENVIRONMENT=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=homework_user
      - DB_PASSWORD=homework_password
      - DB_NAME=homework_tutor
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
    depends_on:
      - mysql
      - redis
      - minio
    networks:
      - homework-network
    restart: unless-stopped

  # 错题本服务
  mistake-service:
    build:
      context: ../../backend/mistake-service
      dockerfile: Dockerfile
    container_name: homework-tutor-mistake-service
    ports:
      - "8082:8082"
    environment:
      - ENVIRONMENT=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=homework_user
      - DB_PASSWORD=homework_password
      - DB_NAME=homework_tutor
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - homework-network
    restart: unless-stopped

  # 聊天服务
  chat-service:
    build:
      context: ../../backend/chat-service
      dockerfile: Dockerfile
    container_name: homework-tutor-chat-service
    ports:
      - "8083:8083"
    environment:
      - ENVIRONMENT=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=homework_user
      - DB_PASSWORD=homework_password
      - DB_NAME=homework_tutor
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - homework-network
    restart: unless-stopped

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: homework-tutor-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - gateway
    networks:
      - homework-network
    restart: unless-stopped

volumes:
  mysql_data:
  postgres_data:
  redis_data:
  minio_data:

networks:
  homework-network:
    driver: bridge
